dash pattern: handling dash patterns < 1
Samsung/thorvg pull request #100
Opened 2020-10-09 01:47 UTC by mgrudzinska

For the dash pattern values (both, length and gap) < 1 the program crashed.
curLen - variable type changed from int to float.

- Description :
For the dash pattern values (both, length and gap) < 1, the program crashes, because it falls into the infinite while loop (the total length of the dashed outline is reduced in each step by a value of zero, so it never gets smaller and the while loop termination condition is never satisfied).

The curLen variable changed to be float type instead of int, as it holds the current value of the plotted pattern, which is a float type.

- Issue Tickets (if any) :

- Tests or Samples (if any) :
Example that crashes without this correction: SmallDashPatterns.cpp
https://github.com/mgrudzinska/thorvg/tree/mgrudzinska/curLen_ex_crash

- Screen Shots (if any) :

2020-10-12 10:33 UTC, hermet commented
@mgrudzinska looks like it won't need to apply dash from the beginning if pattern values are too small ( < FLT_EPSILON).
easily, +  exception handling in the api level.
what doe you think?

2020-10-15 22:54 UTC, mgrudzinska commented
I agree that the dash pattern validation should be done in the api.

2020-10-15 23:16 UTC, mgrudzinska commented on src/lib/sw_engine/tvgSwShape.cpp
> +            if (!dash.curOpGap && dash.curLen > FLT_EPSILON) {
For a pattern like (0,0,3,4) there is no need to add to the outline points for a zero length curve.

2020-10-20 07:11 UTC, hermet requested changes
Please check a comment.

2020-10-20 07:11 UTC, hermet commented on src/lib/tvgShape.cpp
> +    if (dashPattern) {
No, I mean ignore input in the setting side....

2020-10-22 02:39 UTC, hermet requested changes
Please check more comments.

2020-10-22 02:39 UTC, hermet commented on src/lib/tvgShape.cpp
> +    if (dashPattern) {
I mean there is no point that dash has 0 values in the list (insane)
Thus, we can return fail if there is zero values in the list when user call shape->strokeDash().
Then there is no need to handle up above sides.

2020-10-23 08:18 UTC, hermet requested changes
Please check it.

2020-10-23 08:18 UTC, hermet commented on src/lib/sw_engine/tvgSwCommon.h
> +    float curLen;
no reason to change this neither...

2020-10-23 08:42 UTC, merged