capi examples: Added scene API C bindings.
Samsung/thorvg pull request #141
Opened 2020-11-06 08:46 UTC by mihashco

Scene CAPI allows to use scene functionaliy in C applications such as
set opacity to few shapes at one time or implement transparent layers.

@API Additions:
```c
Tvg_Paint* tvg_scene_new();
Tvg_Result tvg_scene_reserve(Tvg_Paint* scene, uint32_t size);
Tvg_Result tvg_scene_push(Tvg_Paint* scene, Tvg_Paint *paint);
```

Examples:
```c
Tvg_Paint *scene = tvg_scene_new();

Tvg_Paint *shape1 = tvg_shape_new();
tvg_shape_append_rect(shape1, 10, 10, 100, 100, 0, 0);
tvg_shape_set_fill_color(shape1, 255, 0, 0, 255);

Tvg_Paint *shape2 = tvg_shape_new();
tvg_shape_append_rect(shape2, 120, 10, 100, 100, 0, 0);
tvg_shape_set_fill_color(shape2, 255, 0, 0, 255);

tvg_scene_push(scene, shape1);
tvg_scene_push(scene, shape2);

tvg_paint_set_opacity(scene, 100);

tvg_canvas_push(canvas, scene);
```

2020-11-09 05:52 UTC, hermet requested changes
Just one comment. please fix it.

2020-11-09 05:52 UTC, hermet commented on inc/thorvg_capi.h
> +/* Picture API                                                          */
Picture API -> Scene API

2020-11-09 15:19 UTC, mihashco commented on inc/thorvg_capi.h
> +/* Picture API                                                          */
Done

2020-11-10 03:13 UTC, hermet approved these changes

2020-11-10 03:13 UTC, merged