common gl_engine: transformation support
Samsung/thorvg pull request #193
Opened 2020-12-21 14:01 UTC by pankajkumar20

- Description : All type of transformations (scale, rotate, translate) supported with gl_engine 

- Issue Tickets (if any) : 

- Tests or Samples (if any) :

- Screen Shots (if any) :

2020-12-22 02:27 UTC, hermet commented
@pankajkumar20 Could you please rebase and PR again?

2020-12-22 10:52 UTC, pankajkumar20 commented
@hermet,  i have rebased & raised PR again, please review it.

2020-12-25 10:55 UTC, hermet requested changes
Origin behaviors are broken after this patch...

2020-12-30 03:22 UTC, hermet approved these changes

2020-12-30 03:23 UTC, merged