Capi: Shape bounds binding
Samsung/thorvg pull request #195
Opened 2020-12-22 14:34 UTC by mmaciola

Added Shape->bounds Capi binding

2020-12-23 01:26 UTC, JSUYA reviewed
In thorvg.h, `bounds` method is declared in `Paint` class.
I think capi should also follow this structure.
What do you think?

2020-12-23 06:31 UTC, hermet requested changes

2020-12-23 06:31 UTC, hermet commented on inc/thorvg_capi.h
> +TVG_EXPORT Tvg_Result tvg_shape_get_bounds(Tvg_Paint* paint, float* x, float* y, float* w, float* h);
=> Tvg_Result tvg_paint_get_bounds(const Tvg_Paint* paint, float* x, float* y, float* w, float* h);

2020-12-24 04:37 UTC, JSUYA approved these changes
LGTM

2020-12-25 10:49 UTC, hermet requested changes
please check a comment.

2020-12-25 10:49 UTC, hermet commented on inc/thorvg_capi.h
> +TVG_EXPORT Tvg_Result tvg_paint_get_bounds(Tvg_Paint* paint, float* x, float* y, float* w, float* h);
Tvg_Paint* paint => const Tvg_Paint* paint,

2020-12-30 03:39 UTC, hermet approved these changes

2020-12-30 03:40 UTC, merged