common render: removed unnecessary assignments in update() fun
Samsung/thorvg pull request #223
Opened 2021-02-01 00:52 UTC by mgrudzinska

Rotation does not change the values of e31 and e32 of the transformation matrix
(augmented matrix for 2D rotation + translation).

The affine transformation matrix (matrix 2D augmented to 3D) has zeros on the positions of indices 3,1 and 3,2. There is no need to recalculate them.

2021-02-01 01:28 UTC, JSUYA approved these changes
LGTM

2021-02-01 01:51 UTC, JSUYA approved these changes
LGTM x2

2021-02-02 02:06 UTC, hermet commented
hmm.. this looks wrong to me. position must be transformed by rotation so that we can support accumulated transform during scene-graph... need to verify it further.

2021-02-02 02:07 UTC, hermet requested changes
looks wrong to me. I will verify it later.

2021-02-02 04:20 UTC, JSUYA commented
> looks wrong to me. I will verify it later.

matrix m is initialized with an identity matrix.
This patch has reduced unnecessary computation.

example)
auto t11 = m.e11 * cosVal + m.e12 * sinVal;
auto t12 = m.e11 * -sinVal + m.e12 * cosVal;
...
m.e12 = t12;
->

m.e11 is 1. and m.e12 is 0.
So..
auto t11 = 1 * cosVal + 0 * sinVal;
auto t12 = 1 * -sinVal + 0 * cosVal;

Therefore, the results of both expressions are the same.

m.e12 = m.e11 * -sinVal;
m.e11 *= cosVal;

The matrix m and the cumulative transformation of this function are not related.
Am I misunderstanding?

2021-02-19 05:02 UTC, hermet commented
> > looks wrong to me. I will verify it later.
> 
> matrix m is initialized with an identity matrix.
> This patch has reduced unnecessary computation.
> 
> example)
> auto t11 = m.e11 * cosVal + m.e12 * sinVal;
> auto t12 = m.e11 * -sinVal + m.e12 * cosVal;
> ...
> m.e12 = t12;
> ->
> 
> m.e11 is 1. and m.e12 is 0.
> So..
> auto t11 = 1 * cosVal + 0 * sinVal;
> auto t12 = 1 * -sinVal + 0 * cosVal;
> 
> Therefore, the results of both expressions are the same.
> 
> m.e12 = m.e11 * -sinVal;
> m.e11 *= cosVal;
> 
> The matrix m and the cumulative transformation of this function are not related.
> Am I misunderstanding?

See how logic is different.

@ before
  auto t13 = m.e13 * cosVal + m.e23 * sinVal;
  m.e13 = t13;
  m.e13 += x;

@after 
  m.e13 = x;

2021-02-19 05:09 UTC, hermet approved these changes

2021-02-19 05:09 UTC, hermet commented
verified no any side effect.

2021-02-19 05:11 UTC, merged