sw_engine common: improving the alpha blending algorithm
Samsung/thorvg pull request #231
Opened 2021-02-03 23:50 UTC by mgrudzinska

Calculations accuracy in ALPHA_BLEND function has been
improved. Until now blending resulted in a slight hue change
(all color channels affected).

2021-02-09 00:28 UTC, hermet commented
@mgrudzinska This could affect eye-catchable performance drop.

Could you please compare test and share the result how it improve the image result? 

I don't like to apply this unless clear enhancement. (saving it for performance)

2021-02-22 02:20 UTC, hermet requested changes
@mgrudzinska This could affect eye-catchable performance drop.

Could you please compare test and share the result how it improves the image result?

I don't like to apply this unless clear enhancement. (saving it for performance)

2021-03-04 01:51 UTC, mgrudzinska commented
I'm sorry it took so long.

Please check the image that you get from the code:
```

2021-04-12 00:02 UTC, mgrudzinska commented
@hermet please check now. This is the method you used in the ALPHA MULTIPLY function.
I don't see any difference between the exact calculation and this approximation, so in my opinion it is sufficient.

However, if you think this change is unnecessary, please close this PR.

2021-05-21 13:35 UTC, hermet commented
@mgrudzinska here is my approach => https://github.com/Samsung/thorvg/pull/386

2021-06-02 12:00 UTC, hermet approved these changes

2021-06-02 12:01 UTC, merged