picture: enabling duplication of the picture with a raw image
Samsung/thorvg pull request #282
Opened 2021-03-10 14:41 UTC by mgrudzinska

duplicate() function worked only for svg images. Now it is possible
to duplicate a Picture with a raw image.

contains changes from #281 

- Tests or Samples :

2021-03-10 14:53 UTC, mgrudzinska commented on src/lib/tvgPictureImpl.h
> +        else if (pixels) dup->pixels = pixels;
is it ok? 

is it possible, that the main Picture will be deleted before the duplicated one? then I'll copy the content

2021-03-11 01:51 UTC, hermet requested changes
Please check a comment.

2021-03-11 01:51 UTC, hermet commented on src/lib/tvgPictureImpl.h
> +    float vw = 0, vh = 0, vx = 0, vy = 0;  //viewbox parameters
i think we can avoid this memory allocation.. guess duplicate could share the source's loader like flyweight.

ie) tvgPictureImpl.h

    Paint* duplicate()
    {
        ...
         dup->loader = loader;
        ...
    }

2021-03-19 10:47 UTC, hermet commented
please check this:
https://github.com/Samsung/thorvg/pull/301

2021-03-19 10:47 UTC, closed without merging