common: fix a potential memory leak after clear()
Samsung/thorvg pull request #382
Opened 2021-05-14 11:27 UTC by hermet

Paints must clear canvas engine data if they were dismissed from the canvas,

1. Canvas::clear(free = false) must retain all the paints from the paints hierarchy
so that user keeps the all dangled paints lifecycle.
In this scenario, it could leak the engine data of paints, this patch fixes it.

2. Previously, t just keeps the immediate paints lives of canvas, but not them of children of scene nor picture.
This patch changes a policy which was not considered seriously,
Now it keeps the all paints lives through the tree-hieararchy.

3. Also changed the Scene::clear() behavior identical to Canvas::clear() for consistency.

@API Modification:

From: Result Scene::clear() noexcept;
To: Result Scene::clear(bool free = true) noexcept;

2021-05-14 13:29 UTC, mihashco requested changes
crash found: 

#1  0x00007ffff433dd06 in tvg::Paint::Impl::dispose (this=0x5555557e63d0, renderer=...) at ../src/lib/tvgPaint.h:90
#2  0x00007ffff4344bdf in tvg::Scene::Impl::clear (this=0x5555557d8e70, free=false) at ../src/lib/tvgSceneImpl.h:183
#3  0x00007ffff4344379 in tvg::Scene::clear (this=0x55555590be80, free=false) at ../src/lib/tvgScene.cpp:67
#4  0x00007ffff436d188 in tvg_scene_clear (scene=0x55555590be80, free=false) at ../src/bindings/capi/tvgCapi.cpp:570
#5  0x00007ffff7763d7c in _efl_canvas_vg_container_efl_object_destructor () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/evas/libevas.so.1
#6  0x00007ffff67cfc8c in efl_destructor () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/../eo/libeo.so.1
#7  0x00007ffff67c5e03 in _efl_del_internal () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/../eo/libeo.so.1
#8  0x00007ffff67c6276 in _efl_unref_internal () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/../eo/libeo.so.1
#9  0x00007ffff67c6d54 in _efl_invalidate () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/../eo/libeo.so.1
#10 0x00007ffff67b999b in _efl_del_internal () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/../eo/libeo.so.1
#11 0x00007ffff67b9e5c in _efl_unref_internal () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/../eo/libeo.so.1
#12 0x00007ffff67c0b5c in efl_unref () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/../eo/libeo.so.1
#13 0x00007ffff775cff5 in efl_replace () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/evas/libevas.so.1
#14 0x00007ffff775d90b in _efl_canvas_vg_object_root_node_set () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/evas/libevas.so.1
#15 0x00007ffff775fff9 in efl_canvas_vg_object_root_node_set () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/evas/libevas.so.1
#16 0x00007ffff7ad550d in _edje_vector_recalc_apply () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/libedje.so.1
#17 0x00007ffff7adb5d3 in _edje_part_recalc () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/libedje.so.1
#18 0x00007ffff7aceb8c in _edje_recalc_table_parts () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/libedje.so.1
#19 0x00007ffff7acec99 in _edje_recalc_do () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/libedje.so.1
#20 0x00007ffff7b80913 in _efl_canvas_layout_efl_canvas_group_group_calculate () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/libedje.so.1
#21 0x00007ffff76b2cc9 in efl_canvas_group_calculate () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/evas/libevas.so.1
#22 0x00007ffff76b0921 in evas_call_smarts_calculate () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/evas/libevas.so.1
#23 0x00007ffff771d40f in evas_render_updates_internal () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/evas/libevas.so.1
#24 0x00007ffff7721014 in _evas_canvas_render_async () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/evas/libevas.so.1
#25 0x00007ffff7676ea2 in evas_canvas_render_async () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/evas/libevas.so.1
#26 0x00007ffff767a0b1 in evas_render_async () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/evas/libevas.so.1
#27 0x00007fffe9c64ebd in _ecore_evas_x_render () from /usr/local/lib/x86_64-linux-gnu/ecore_evas/engines/x/v-1.25/module.so
#28 0x00007ffff708fff2 in _ecore_evas_idle_enter () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/ecore_evas/libecore_evas.so.1
#29 0x00007ffff72d7bc0 in _ecore_call_task_cb () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/ecore/libecore.so.1
#30 0x00007ffff72d7c28 in _ecore_factorized_idle_process () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/ecore/libecore.so.1
#31 0x00007ffff67cc48e in _event_callback_call () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/../eo/libeo.so.1
#32 0x00007ffff67cc697 in _efl_object_event_callback_call () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/../eo/libeo.so.1
#33 0x00007ffff67cc74c in efl_event_callback_call () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/edje/../eo/libeo.so.1
#34 0x00007ffff72dca50 in _ecore_main_loop_iterate_internal () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/ecore/libecore.so.1
#35 0x00007ffff72d9f2d in _ecore_main_loop_begin () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/ecore/libecore.so.1
#36 0x00007ffff72e20bb in _efl_loop_begin () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/ecore/libecore.so.1
#37 0x00007ffff72e45ca in efl_loop_begin () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/ecore/libecore.so.1
#38 0x00007ffff72da0eb in ecore_main_loop_begin () from /home/m.szczecinsk/Work/efl-mainline/build/src/examples/edje/../../lib/ecore/libecore.so.1
#39 0x00005555555567cb in main ()
(gdb) f 1
#1  0x00007ffff433dd06 in tvg::Paint::Impl::dispose (this=0x5555557e63d0, renderer=...) at ../src/lib/tvgPaint.h:90
90	            return smethod->dispose(renderer);
(gdb) print this
$1 = (tvg::Paint::Impl * const) 0x5555557e63d0
(gdb) print *this
$2 = {smethod = 0x555555926650, rTransform = 0x555555926650, flag = 0, cmpTarget = 0x0, cmpMethod = tvg::CompositeMethod::None, opacity = 255 '\377', type = tvg::PaintType::Shape}
(gdb) print *this->smethod 
$3 = {_vptr.StrategyMethod = 0x5555557a8cb0}
(gdb) f 0 
#0  0x0000000000000041 in ?? ()
(gdb) f1 
Undefined command: "f1".  Try "help".
(gdb) f 1 
#1  0x00007ffff433dd06 in tvg::Paint::Impl::dispose (this=0x5555557e63d0, renderer=...) at ../src/lib/tvgPaint.h:90
90	            return smethod->dispose(renderer);
(gdb) print renderer 
$4 = (tvg::RenderMethod &) @0x55555585fb90: {_vptr.RenderMethod = 0x7ffff456f628 <vtable for tvg::SwRenderer+16>}
(gdb) print smethod 
$5 = (tvg::StrategyMethod *) 0x555555926650
(gdb) print *smethod 
$6 = {_vptr.StrategyMethod = 0x5555557a8cb0}
(gdb) print smethod->dispose 
Cannot take address of method dispose.






#39 0x00005555555567cb in main ()
(gdb) f 1
#1  0x00007ffff433dd06 in tvg::Paint::Impl::dispose (this=0x5555557e63d0, renderer=...) at ../src/lib/tvgPaint.h:90
90	            return smethod->dispose(renderer);
(gdb) print this
$1 = (tvg::Paint::Impl * const) 0x5555557e63d0
(gdb) print *this
$2 = {smethod = 0x555555926650, rTransform = 0x555555926650, flag = 0, cmpTarget = 0x0, cmpMethod = tvg::CompositeMethod::None, opacity = 255 '\377', type = tvg::PaintType::Shape}
(gdb) print *this->smethod 
$3 = {_vptr.StrategyMethod = 0x5555557a8cb0}
(gdb) f 0 
#0  0x0000000000000041 in ?? ()
(gdb) f1 
Undefined command: "f1".  Try "help".
(gdb) f 1 
#1  0x00007ffff433dd06 in tvg::Paint::Impl::dispose (this=0x5555557e63d0, renderer=...) at ../src/lib/tvgPaint.h:90
90	            return smethod->dispose(renderer);
(gdb) print renderer 
$4 = (tvg::RenderMethod &) @0x55555585fb90: {_vptr.RenderMethod = 0x7ffff456f628 <vtable for tvg::SwRenderer+16>}
(gdb) print smethod 
$5 = (tvg::StrategyMethod *) 0x555555926650
(gdb) print *smethod 
$6 = {_vptr.StrategyMethod = 0x5555557a8cb0}
(gdb) print smethod->dispose 
Cannot take address of method dispose.

2021-05-17 10:58 UTC, hermet commented
> Crash code sample [mihashco@a8fffac](https://github.com/mihashco/thorvg/commit/a8fffac3bd1559b7e7a0b16f271582448ad56d11)
> 
> ```
> 0x00007ffff7f94e75 in tvg::Scene::Impl::~Impl (this=0x55555589dc90, __in_chrg=<optimized out>) at ../src/lib/tvgSceneImpl.h:41
> 41	            delete(*paint);
> (gdb) bt
> #0  0x00007ffff7f94e75 in tvg::Scene::Impl::~Impl (this=0x55555589dc90, __in_chrg=<optimized out>) at ../src/lib/tvgSceneImpl.h:41
> #1  0x00007ffff7f94cd2 in tvg::Scene::~Scene (this=0x55555589dc30, __in_chrg=<optimized out>) at ../src/lib/tvgScene.cpp:37
> #2  0x00007ffff7f94d10 in tvg::Scene::~Scene (this=0x55555589dc30, __in_chrg=<optimized out>) at ../src/lib/tvgScene.cpp:38
> #3  0x00007ffff7fbd825 in tvg_paint_del (paint=0x55555589dc30) at ../src/bindings/capi/tvgCapi.cpp:146
> #4  0x0000555555556883 in testCapi () at ../src/examples/Crash.cpp:76
> #5  0x0000555555556beb in main (argc=1, argv=0x7fffffffdd38) at ../src/examples/Crash.cpp:136
> ```

I checked your sample and it works correctly. the crash is caused wrong sample implementation. It must be fixed like this:

solution 1:
//  tvg_paint_del(shape); 
  tvg_paint_del(scene2); 
solution 2:
  tvg_paint_del(shape); 
  tvg_scene_clear(scene2, false);
  tvg_paint_del(scene2);

2021-05-26 03:53 UTC, hermet commented
https://github.com/Samsung/thorvg/issues/352

2021-05-28 07:18 UTC, mihashco approved these changes

2021-05-28 07:19 UTC, merged