utc capi: Added shape fill utc.
Samsung/thorvg pull request #412
Opened 2021-06-04 08:13 UTC by mihashco

2021-06-04 09:01 UTC, hermet requested changes
Please check comments.

2021-06-04 09:01 UTC, hermet commented on test/capi/testFill.cpp
> +#define WIDTH  100
please do not use macro in test unless it helps the reduce  LOC.

2021-06-04 09:35 UTC, mihashco commented on test/capi/testFill.cpp
> +#include <stdint.h>
yes it is for uint8_t

2021-06-04 09:35 UTC, mihashco commented on test/capi/testFill.cpp
> +#define WIDTH  100
removed

2021-06-07 04:19 UTC, JSUYA commented on test/capi/testFill.cpp
> +TEST_CASE("CAPI: set_get_fill_color_valid", "[capi-fill]")
Hi, "CAPI: " is unnecessary.

2021-06-07 08:11 UTC, hermet requested changes
please keep the consistency for the naming of TEST_CASE()

2021-06-07 08:11 UTC, hermet commented on test/capi/testFill.cpp
> +TEST_CASE("CAPI: set_get_fill_color_valid", "[capi-fill]")
please keep the consistency for the naming of TEST_CASE()

2021-06-07 08:11 UTC, hermet commented
each of your patches have different naming of TEST_CASE(), please keep its consistency.

2021-06-11 14:41 UTC, hermet approved these changes

2021-06-11 14:41 UTC, hermet commented on test/capi/testFill.cpp
> + * Copyright (c) 2020-2021 Samsung Electronics Co., Ltd. All rights reserved.
2021

2021-06-11 14:42 UTC, merged