utc capi: Added linear gradient tests.
Samsung/thorvg pull request #418
Opened 2021-06-04 13:05 UTC by mihashco

2021-06-07 10:21 UTC, hermet requested changes

2021-06-07 10:21 UTC, hermet commented on test/capi/testLinearGradient.cpp
> +#include <stdint.h>
-- unnecessary

2021-06-07 10:21 UTC, hermet commented on test/capi/testLinearGradient.cpp
> + * Copyright (c) 2020-2021 Samsung Electronics Co., Ltd. All rights reserved.
2021

2021-06-07 10:21 UTC, hermet commented on test/capi/testLinearGradient.cpp
> +TEST_CASE("Basic Create", "[capi-radial-gradient]")
please use naming.
capiRadialGradient

2021-06-08 11:32 UTC, mgrudzinska commented on test/capi/testLinearGradient.cpp
> +
I would use different values for each arg so we could catch mistakes like switching the variables (ex x1 with y1 etc)

2021-06-17 05:47 UTC, merged