tvg_saver: saver implementation
Samsung/thorvg pull request #432
Opened 2021-06-10 09:37 UTC by mgrudzinska

please be aware it's a draft

2021-06-22 05:34 UTC, hermet requested changes
Please have a look.

2021-06-22 05:34 UTC, hermet commented on src/lib/tvgPaint.h
> +        unique_ptr<Saver> saver = nullptr;
I think we should not keep this saver since it's not common case. it can be used temporarily.

2021-06-22 05:34 UTC, hermet commented on src/lib/tvgPaint.h
> +                paintDataByteCnt += tvgSaver->saveMember(TVG_PAINT_OPACITY_INDICATOR,
Please one line. for CODE CONSISTENCY.

2021-06-22 05:34 UTC, hermet commented on src/lib/tvgPaint.h
> +                                                         sizeof(rTransform->m), &rTransform->m);
Please one line. for CODE CONSISTENCY.

2021-06-22 05:34 UTC, hermet commented on src/lib/tvgSaver.h
> +    virtual bool write() = 0;
My gut says it must be this:
virtual bool open(path);     //open the file and return its result.
virtual bool write(paint);    //write data and return the result.

2021-06-22 05:34 UTC, hermet commented on src/savers/tvg/tvgTvgSaver.h
> + * Copyright (c) 2020 Samsung Electronics Co., Ltd. All rights reserved.
2021

2021-06-22 05:34 UTC, hermet commented on src/savers/meson.build
> +
See how loaders do this:

if get_option('loaders').contains('tvg') == true
    subdir('tvg')
    message('Enable TVG Loader')
endif

2021-06-22 05:34 UTC, hermet commented on src/savers/tvg/tvgTvgSaver.cpp
> + * Copyright (c) 2020 Samsung Electronics Co., Ltd. All rights reserved.
2021

2021-06-22 05:34 UTC, hermet commented on src/savers/tvg/tvgTvgSaver.cpp
> +    // MGS - metadata not raelly used for now - type hardcoded (to be changed)
if it's not used, remove it. we can improve this by adding checkSum mechanism later.

2021-06-22 05:34 UTC, hermet commented on src/savers/tvg/tvgTvgSaver.h
> +    char* bufferPosition = nullptr;
please use "pointer" as same as loader's

2021-06-22 05:34 UTC, hermet commented on src/savers/tvg/tvgTvgSaver.h
> +    char* buffer = nullptr;
data = nullptr;

2021-06-22 05:34 UTC, hermet commented on src/savers/tvg/tvgTvgSaver.h
> +    Paint* root;
root = nullptr;

2021-06-22 05:34 UTC, hermet commented on src/savers/tvg/tvgTvgSaver.h
> +    string filePath;
filePath => path

2021-06-22 05:34 UTC, hermet commented on src/savers/tvg/tvgTvgSaver.h
> +//private:
remove it if unnecessary.

2021-06-25 00:09 UTC, mgrudzinska commented
replaced by a different approach - pr #511

2021-06-25 00:09 UTC, closed without merging