tvg_saver: example
Samsung/thorvg pull request #512
Opened 2021-06-25 00:37 UTC by mgrudzinska

I'll improve the example - for now you can use it to test if you need.

2021-06-28 19:18 UTC, mgrudzinska commented
I removed white spaces

2021-07-19 08:40 UTC, hermet requested changes
very poor commit message, and please atomic patch as possible.

2021-07-19 11:10 UTC, mgrudzinska commented
I've removed changes from meson.build and changed the msg. please check now

2021-07-20 04:38 UTC, hermet approved these changes

2021-07-20 04:38 UTC, merged