sw_engine: preventing the double application of the opacity
Samsung/thorvg pull request #540
Opened 2021-06-30 14:13 UTC by mgrudzinska

For filled and stroked shapes with a gradient, the opacity
was applied during the composition and during the ctable update.
To prevent this, in case the composition occurred, ctable
is updated with the opacity = 255.

before:
![8before](https://user-images.githubusercontent.com/67589014/123975459-a37f3000-d9bd-11eb-9d83-0977d70f81b5.PNG)

after:
![8after](https://user-images.githubusercontent.com/67589014/123975265-7cc0f980-d9bd-11eb-9df1-7ec0d992c9a7.PNG)

code:
```
    auto shape = tvg::Shape::gen();
    shape->appendRect(0, 0, 800, 800, 0, 0);
    shape->fill(255, 0, 0, 255);
    if (canvas->push(move(shape)) != tvg::Result::Success) return;

    tvg::Fill::ColorStop colorStops[2];
    colorStops[0] = {0, 0, 0, 255, 255};
    colorStops[1] = {1, 0, 0, 255, 255};

    auto shape1 = tvg::Shape::gen();
    shape1->appendRect(410, 0, 180, 180, 10, 10);

    auto fill = tvg::LinearGradient::gen();
    fill->linear(0, 0, 800, 800);
    fill->colorStops(colorStops, 2);

    shape1->fill(move(fill));
    shape1->opacity(100);
    shape1->stroke(10);

    fill = tvg::LinearGradient::gen();
    fill->linear(0, 0, 800, 800);
    fill->colorStops(colorStops, 2);

    shape1->stroke(move(fill));
    if (canvas->push(move(shape1)) != tvg::Result::Success) return;

    auto shape2 = tvg::Shape::gen();
    shape2->appendRect(610, 0, 180, 180, 10, 10);
    shape2->fill(0, 0, 255, 255);
    shape2->opacity(100);
    shape2->stroke(10);
    shape2->stroke(0, 0, 255, 255);
    if (canvas->push(move(shape2)) != tvg::Result::Success) return;

    shape1 = tvg::Shape::gen();
    shape1->appendRect(410, 210, 180, 180, 40, 40);

    shape1->fill(0, 0, 255, 255);
    shape1->opacity(100);
    shape1->stroke(30);

    fill = tvg::LinearGradient::gen();
    fill->linear(0, 0, 800, 800);
    fill->colorStops(colorStops, 2);

    shape1->stroke(move(fill));
    if (canvas->push(move(shape1)) != tvg::Result::Success) return;

    shape2 = tvg::Shape::gen();
    shape2->appendRect(610, 210, 180, 180, 40, 40);

    fill = tvg::LinearGradient::gen();
    fill->linear(0, 0, 800, 800);
    fill->colorStops(colorStops, 2);

    shape2->fill(move(fill));
    shape2->opacity(100);
    shape2->stroke(30);

    shape2->stroke(0, 0, 255, 255);
    if (canvas->push(move(shape2)) != tvg::Result::Success) return;
```

2021-07-01 05:26 UTC, hermet requested changes
Please check comments.

2021-07-01 05:26 UTC, hermet commented on src/lib/sw_engine/tvgSwRenderer.cpp
> -                    if (!shapeGenStrokeFillColors(&shape, fill, transform, surface, opacity, ctable)) goto err;
In this context, stroking is always true

Contextual function calls generates more cpu instructions, you can write it one line.
shapeGenStrokeFillColors(........, (filling ? 255 : opacity), ...) goto err;
or
auto opacity2 = filling ? 255 : opacity;
shapeGenStrokeFillColors(........, opacity2, ...) goto err;

2021-07-01 05:26 UTC, hermet commented on src/lib/sw_engine/tvgSwRenderer.cpp
> +                    else if (!shapeGenStrokeFillColors(&shape, fill, transform, surface, opacity, ctable)) goto err;
coding convention error.

2021-07-01 05:26 UTC, hermet commented on src/lib/sw_engine/tvgSwRenderer.cpp
> +            if (stroking && filling) {
auto opacity2 = (stroking && filling) ? 255 : opacity;
shapeGenStrokeFillColors(........, opacity2, ...) goto err;

2021-07-01 05:26 UTC, hermet commented on src/lib/sw_engine/tvgSwRenderer.cpp
> +        bool validFill = false;
i think filling can be used instead.

2021-07-01 05:26 UTC, hermet commented on src/lib/sw_engine/tvgSwRenderer.cpp
> +            if (sdata->fill()) {
if (sdata->fill()) filling = true;
else shapeDelFill(&shape);

2021-07-01 05:26 UTC, hermet commented on src/lib/sw_engine/tvgSwRenderer.cpp
>          //Fill
Update comment: => Figuring out Filling in advance.

2021-07-13 13:14 UTC, mgrudzinska commented
@hermet please check it after #606 and #607 are merged. here are only two lines changed if you compare to the file after its refactoring in these two prs.

2021-07-13 13:15 UTC, mgrudzinska commented on src/lib/sw_engine/tvgSwRenderer.cpp
> +                    if (!shapeGenStrokeFillColors(&shape, fill, transform, surface, visibleFill ? 255 : opacity, ctable)) goto err;
changed: ```visibleFill ? 255 : opacity```

2021-07-15 15:45 UTC, hermet requested changes
Tip: Refactoring / Bug fix can be separated when you request a code review...

2021-07-15 15:45 UTC, hermet commented on src/lib/sw_engine/tvgSwRenderer.cpp
> -                    if (!shapeGenRle(&shape, sdata, antiAlias, clips.count > 0 ? true : false)) goto err;
This looks wrong, shape rle is necessary even though only the stroking is valid but you changed it to when the filling is valid....

2021-07-15 15:47 UTC, hermet commented
@mgrudzinska when you request a review to fix a core-side bug, please make an atomic patch by less modifying as possible.

2021-07-15 15:51 UTC, mgrudzinska commented
@hermet I make a note that these changes are in 606 and 607 and here I add only 2 lines when compare to them. sorry for making it confusing.

2021-07-19 07:02 UTC, hermet approved these changes

2021-07-19 07:02 UTC, merged