svg_loader: multiple composition memory leak
Samsung/thorvg pull request #556
Opened 2021-07-01 09:31 UTC by mmaciola

Multiple composition are still not supported, but this patch fixes a
memory leak if it is tried to be applied.

2021-07-01 11:56 UTC, hermet requested changes

2021-07-01 11:56 UTC, hermet commented on src/loaders/svg/tvgSvgLoader.cpp
>  #endif
how about return here immediately?

2021-07-02 04:31 UTC, JSUYA reviewed
I think you probably copied the logic of `_handleMaskAttr`. If you want to change that function return immediately, the mask case should be modified in the same way.

2021-07-03 05:13 UTC, hermet approved these changes

2021-07-03 05:14 UTC, merged