sw_engine common: Added neon version of rasterRGBA32 API.
Samsung/thorvg pull request #664
Opened 2021-07-27 11:56 UTC by mihashco

Changes:
- Added 'neon' vector option in build system
- Introduced neon version of rasterRGBA32 API, which improves speed of the function on ARM cpu's around ~35% (measured on 800x800 array of uint32_t)

2021-07-27 12:57 UTC, mmaciola approved these changes

2021-07-28 03:48 UTC, hermet commented
@mihashco did you test on real device?

2021-07-28 04:12 UTC, hermet requested changes
Please fix nitpicks :+1:

2021-07-28 04:12 UTC, hermet commented on src/lib/sw_engine/tvgSwCommon.h
> +    for (i = 0; i < iterations; ++i) {
please fix convention:
for (uint32_t i = 0; ...)

2021-07-28 04:12 UTC, hermet commented on src/lib/sw_engine/tvgSwCommon.h
> +    uint32_t neon_filled = iterations * 4;
please fix convention:
neon_filled => neonFilled

2021-07-28 04:12 UTC, hermet commented on src/lib/sw_engine/tvgSwCommon.h
> +    while(left--) *dst++ = val;
please fix convention:
while^(left

2021-07-28 04:35 UTC, mihashco commented
> @mihashco did you test on the real device?

yes, I tested this function and checked its result on arm. Also thorVG with this funciton was tested on ARM.

2021-07-28 10:17 UTC, hermet approved these changes

2021-07-28 10:17 UTC, merged