sw_engine: fix missing alpha blending for images
Samsung/thorvg pull request #670
Opened 2021-07-28 12:57 UTC by mmaciola

There were a missing alpha blending for images that resulted in flipping to the next byte after adding dst pixels.
@issue: #655

2021-07-29 02:43 UTC, hermet commented
hmm it looks image source is not applied in pre-multiplied alpha...  how do we figure it out from the source.

2021-07-30 01:42 UTC, JSUYA commented
Are there no cases that alpha(opacity) is applied as a duplicate?
Need to some more check..

2021-08-06 14:55 UTC, mmaciola commented
No problems regarding the opacity and duplication were found
```
    auto picture = tvg::Picture::gen();
    picture->load("/home/mmaciola_local/Downloads/icon_play.png");
    picture->size(200, 200);

    auto picture2 = unique_ptr<tvg::Picture>(static_cast<tvg::Picture*>(picture->duplicate()));
    picture2->translate(200, 0);
    picture2->opacity(128);

    auto picture3 = unique_ptr<tvg::Picture>(static_cast<tvg::Picture*>(picture2->duplicate()));
    picture3->translate(400, 0);
    picture3->opacity(255);

    if (canvas->push(move(picture)) != tvg::Result::Success) return;
    if (canvas->push(move(picture2)) != tvg::Result::Success) return;
    if (canvas->push(move(picture3)) != tvg::Result::Success) return;
```
![Screenshot from 2021-08-06 16-54-10](https://user-images.githubusercontent.com/71131832/128529732-aa3da2a5-ecba-4697-97ac-174ae1fb6003.png)

2021-08-11 06:10 UTC, JSUYA reviewed
Sorry for the very late review.
This alpha addition calculation should also be applied to other image rasterize code like _rasterImageRle, translucentImage etc.
(+ recently added Upscale raster function)

2021-09-02 08:20 UTC, JSUYA commented
hmm.. as far as I understand.. for this code to work, all images we use must be non-premultiplied color. 

According to libpng's manual(http://www.libpng.org/pub/png/libpng-manual.txt), it seems that we can get a pemultiplied image by using png_set_alpha_mode(..., PNG_ALPHA_PREMULTIPLIED,...) before loading the image. (I may have misunderstood :( .. ) 
But it looks like we need to read using png_structp rather than simplified API (png_image and etc...) for this operation.

@hermet What do you think?

2021-09-03 02:43 UTC, hermet commented
We need a unified method from the loader to pass the pixel data in one uniform.
Currently, sw raster engine is supposed to do accept only premultiplied values to avoid additional blending computation.
So I think imaeg loaders(which has alpha channel) needs to prepare premultiplied pixels. 
So... yes. (@JSUYA good catch) we can try use that option whether it's available.

fyi, raster engine might need an option to deal both premultiplied & non-premultipled pixels in the end but not this stage.

@mmaciola please check @JSUYA's suggestion.

2021-09-03 02:44 UTC, hermet requested changes
Please check the conversation.

2021-09-03 15:25 UTC, closed without merging

2021-09-06 08:11 UTC, mmaciola commented
Thanks @JSUYA for suggestion. I have to investigate `png_set_alpha_mode` and the possibility of using it when using a simplified API of libpng