loaders: Pass mimetype to picture::load
Samsung/thorvg pull request #678
Opened 2021-08-03 12:10 UTC by mmaciola

Added mimetype attribute to enfaster loading using a proper loader.

@Changed api: Picture::load(const char* data, uint32_t size, const std::string& mimeType, bool copy = false)
@issue: #571

2021-08-04 02:07 UTC, JSUYA reviewed
How about keeping original API together?
`Result load(const char* data, uint32_t size, bool copy = false)`
I don't think it is essential.

2021-08-04 10:48 UTC, hermet requested changes
Please check comments.

2021-08-04 10:48 UTC, hermet commented on inc/thorvg.h
> +     * @param[in] mimetype Mimetype of data. If null or unknown loaders will be tried one by one.
We can provide better explicit description.

Mimetype of data => Mimetype of data such as "jpg", "svg", "png", etc.

If null => If empty string or @c nullptr

2021-08-04 10:48 UTC, hermet commented on inc/thorvg.h
> -    Result load(const char* data, uint32_t size, bool copy = false) noexcept;
This api must be retained for the compatibility. You can deprecate it or just leave it now.

2021-08-04 13:01 UTC, mmaciola commented
@hermet @JSUYA fixed according to the comments.
Original api `Result load(const char* data, uint32_t size, bool copy = false)` kept with deprecated note

2021-08-05 02:02 UTC, hermet approved these changes

2021-08-05 02:02 UTC, merged