common picture: changed x and y values returned by the bounds api
Samsung/thorvg pull request #793
Opened 2021-09-09 23:16 UTC by mgrudzinska

For an svg file, the bounds are established by the viewbox values.

For shapes we establish not only the width and height as the bounds, but also the starting points.
For raw pictures or pngs, the starting points are zeros, but for an svg it can be any value.
This change could help us with removing in the future the viewbox api.

2021-09-09 23:23 UTC, mgrudzinska commented
I'll change the test tomorrow, after you'll comment that this change makes sense to you

2021-09-14 11:59 UTC, hermet requested changes

2021-09-14 11:59 UTC, hermet commented on src/lib/tvgPictureImpl.h
> +        if (x) *x = loader->vx;
viewbox is only available to svg.
we can't assume these values are always valid.

I know... current bounds() api has an issue. 
This is also regarded to this issue. https://github.com/Samsung/thorvg/issues/746

Need to think about fundamental solution...

2021-09-15 11:18 UTC, mgrudzinska commented
#805 is enough for now

2021-09-15 11:18 UTC, closed without merging