infra: add all option to enable all loader formats.
Samsung/thorvg pull request #859
Opened 2021-10-01 09:58 UTC by hermet

just for developer convenience (including me)

2021-10-01 12:32 UTC, mgrudzinska requested changes
1. meson.build in src/loaders has to be edited as well
2. I'd keep `''` as an option (no loaders)

in general I find this change very very useful :)

2021-10-05 09:05 UTC, hermet commented
>     1. meson.build in src/loaders has to be edited as well
> 
>     2. I'd keep `''` as an option (no loaders)
> 
> 
> in general I find this change very very useful :)

ok, makes sense! thanks.

2021-10-05 09:14 UTC, mgrudzinska approved these changes

2021-10-05 10:07 UTC, mmaciola approved these changes

2021-10-06 02:13 UTC, merged