sw_engine: var/funct renaming and moving some conditions
Samsung/thorvg pull request #975
Opened 2021-11-01 12:30 UTC by mgrudzinska

Changed names:
shape->rect -> shape->fastTrack
_factTrack -> _axisAlignedRect

The check whether a shape is an axis aligned rectangle should be done
only if the shape has no clips.

(a shape can be a rect but still its `fastTrack` can be false)

2021-11-01 12:59 UTC, hermet requested changes
Thanks for your effort but please fix a bug, then coming again with a separate code refactoring... (or vice versa)
This kind of code refactoring change is too digression. (Meaning that, hard to catch the core part by the reviewers... Not good habit.)

2021-11-01 13:17 UTC, mgrudzinska commented
@hermet please check #977, here I'll do only the refactoring, after #977 is merged

2021-11-01 13:21 UTC, hermet commented
> @hermet please check #977, here I'll do only the refactoring, after #977 is merged

#977 has been applied. thanks.

2021-11-02 02:41 UTC, hermet approved these changes
thanks.

2021-11-02 02:41 UTC, merged